export const countryMap = {
  BO: "Bolivia, Plurinational State of",
  CG: "Congo, Republic of the",
  KP: "North Korea",
  KR: "South Korea",
  MD: "Moldova, Republic of",
  RU: "Russia",
  VA: "Holy See",
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AD: "Andorra",
  AO: "Angola",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BT: "Bhutan",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  KM: "Comoros",
  CD: "Congo, Democratic Republic of the",
  CR: "Costa Rica",
  CI: "Côte d'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czechia",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GR: "Greece",
  GD: "Grenada",
  GT: "Guatemala",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HU: "Hungary",
  HK: "Hong Kong",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MR: "Mauritania",
  MU: "Mauritius",
  MX: "Mexico",
  FM: "Micronesia, Federated States of",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  MK: "North Macedonia",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RW: "Rwanda",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  AQ: "Antarctica",
  AS: "American Samoa",
  AX: "Åland Islands",
  BM: "Bermuda",
  MO: "Macao",
  PS: "Palestine, State of",
  PR: "Puerto Rico",
  TW: "Taiwan",
  XK: "Kosovo",
};

export const getCountryName = (code: string) => {
  return countryMap[code.toUpperCase()] || code;
};

export const deviceMap = {
  // 你提供的初始型号
  K: "K",
  CPH1923: "OPPO A1k",
  "1820": "Nokia 6.1",
  V2111: "Vivo Y70s",
  CPH2471: "OPPO A58",
  M2006C3LG: "Redmi 9A",
  CPH2269: "OPPO A54",
  CPH2185: "OPPO A15",
  "1904": "Nokia 3.2",

  // OPPO 常见型号 (部分基于 CPH/PDxM 系列)
  CPH2179: "OPPO A53",
  CPH2239: "OPPO A16",
  CPH2365: "OPPO A77 5G",
  CPH2385: "OPPO A57",
  CPH2449: "OPPO Find X5 Pro",
  CPH2451: "OPPO Find X5",
  CPH2521: "OPPO Reno11 5G",
  CPH2573: "OPPO Reno12 Pro 5G",
  CPH2591: "OPPO Find X8 Pro",
  CPH2593: "OPPO Find X8",

  // Vivo 常见型号 (部分基于 V/PD 系列)
  V2040: "Vivo Y70",
  V2130: "Vivo Y33s",
  V2145: "Vivo Y21",
  V2236: "Vivo Y16",
  V2307: "Vivo Y28 5G",
  V2333: "Vivo Y78 5G",
  V2349: "Vivo X100",
  V2309A: "Vivo X100 Pro",
  V2239: "Vivo V29",
  V2250: "Vivo V30 Pro",

  // 小米/Redmi 常见型号 (部分基于 M/220x 系列)
  M2007J20CG: "Redmi Note 9",
  M2010J19CG: "Redmi Note 9 Pro",
  M2101K7AG: "Redmi Note 10",
  M2103K19G: "Redmi Note 10 Pro",
  M2004J19C: "Redmi 9",
  "2201117TG": "Redmi Note 11",
  "23021RAAEG": "Xiaomi 13",
  "23127PN0CG": "Redmi Note 13 Pro",
  "24053PY09G": "Redmi Note 14 5G",
  "2210132G": "Xiaomi 12 Pro",

  // 诺基亚 常见型号
  "TA-1020": "Nokia 5",
  " TA-1030": "Nokia 3",
  "TA-1174": "Nokia 7.2",
  "TA-1333": "Nokia 5.4",
  "TA-1398": "Nokia G20",
  "TA-1529": "Nokia G42 5G",
  "TA-1485": "Nokia 2660 Flip",
  "TA-1551": "Nokia XR21",

  // 三星 常见型号 (基于 SM- 系列)
  "SM-G960F": "Samsung Galaxy S9",
  "SM-G973F": "Samsung Galaxy S10",
  "SM-A515F": "Samsung Galaxy A51",
  "SM-A525F": "Samsung Galaxy A52",
  "SM-G998B": "Samsung Galaxy S21 Ultra",
  "SM-S911B": "Samsung Galaxy S23",
  "SM-A356E": "Samsung Galaxy A35 5G",
  "SM-M556B": "Samsung Galaxy M55 5G",

  // 华为 常见型号 (基于 ANA/STF 系列)
  "ANA-AN00": "Huawei Mate 30 5G",
  "STF-AL10": "Huawei Mate 10",
  "VOG-AL00": "Huawei P30",
  "JNY-LX1": "Huawei P40 Lite",
  "LYA-L29": "Huawei Mate 20 Pro",
  "TAS-AL00": "Huawei Mate 50",
  "DBR-W10": "Huawei MatePad 11", // 平板示例

  // 苹果 常见型号 (基于内部标识符)
  "iPhone11,8": "iPhone XR",
  "iPhone12,1": "iPhone 11",
  "iPhone13,2": "iPhone 12",
  "iPhone14,5": "iPhone 13",
  "iPhone15,2": "iPhone 14 Pro",
  "iPhone16,1": "iPhone 15 Pro", // 2023 机型

  // OnePlus 常见型号
  IN2013: "OnePlus 8",
  KB2000: "OnePlus 8T",
  LE2123: "OnePlus 9 Pro",
  CPH2551: "OnePlus 12",
  CPH2611: "OnePlus Nord 4",

  // Realme 常见型号
  RMX3370: "Realme GT Neo 2",
  RMX3686: "Realme Narzo 60",
  RMX3830: "Realme C53",
  RMX3998: "Realme 12 Pro 5G",
  RMX3890: "Realme GT 6",
};

export const getDeviceName = (model: string) => {
  return deviceMap[model.toUpperCase()] || model;
};
