export const Team_Plan_Quota = {
  free: {
    SL_TrackedClicks: 100000,
    SL_NewLinks: 1000,
    SL_AnalyticsRetention: 180,
    SL_Domains: 1,
    SL_AdvancedAnalytics: true,
    RC_NewRecords: 3,
    EM_EmailAddresses: 1000,
    EM_Domains: 1,
    APP_Support: "basic",
    APP_ApiAccess: true,
  },
  premium: {
    SL_TrackedClicks: 10000000,
    SL_NewLinks: 10000,
    SL_AnalyticsRetention: 360,
    SL_Domains: 3,
    SL_AdvancedAnalytics: true,
    RC_NewRecords: 3,
    EM_EmailAddresses: 10000,
    EM_Domains: 3,
    APP_Support: "live",
    APP_ApiAccess: true,
  },
  business: {
    SL_TrackedClicks: 10000000,
    SL_NewLinks: 10000,
    SL_AnalyticsRetention: 360,
    SL_Domains: 3,
    SL_AdvancedAnalytics: true,
    RC_NewRecords: 3,
    EM_EmailAddresses: 10000,
    EM_Domains: 3,
    APP_Support: "live",
    APP_ApiAccess: true,
  },
};
